version: '2'
services:
  web:
    build: .
    ports:
      - "9393:9300"
    environment:
      - CSVSERVER_BORDER=Orange
  prometheus:
    image: prom/prometheus:v2.22.0
    depends_on:
      - web
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml:ro

    command:
       - '--config.file=/etc/prometheus/prometheus.yaml'

